### ISSUE TITLE
Create and send invitation

### ISSUE THREAD

**Issue by vmbrasseur** [dcppc/dcppc-workshops#4]
- [x] Write Tito event text (see #3)
- [x] Set up Tito RSVP form
- [x] Confirm distribution list
-  ~~Get distro list into Tito?~~
- [x] Send invite to:
       - [x]  [Leads](leads@dcppc.groups.io)
       - [x]  [Project Contacts](contacts@dcppc.groups.io) (see [also](https://github.com/dcppc/organize/blob/master/onboarding/teams.md)) and have them forward to their teams
         - [x] data stewards (Cathy Laurie, Mike Cherry, Mary Shimoyama, and Kristin Ardlie) data-stewards@dcppc.groups.io
         - [ x] Vivien & Tonya

Information required for the event text:

- [x] Location, incl address
- [x] Dates & times
- [x] [General description of event format](https://github.com/dcppc/dcppc-workshops/issues/9)
- [x] Blurb stating all travel is funded
- [x] Blurb stating all team members welcome (not simply PIs)
- [x] [Code of Conduct](https://github.com/dcppc/dcppc-workshops/issues/1)

Information required for the RSVP form:

- [x] Name, title
- [x] CoC agreement checkbox
- [x] Agreement to record lightning talks checkbox
- [x] Institution
- [x] KC/Team
- [x] Dietary restrictions
- [x] confirm program format

**Comment by raynamharris** [comment]
I don't have access to tito but i can assist

**Comment by vmbrasseur** [comment]
I've started setting up the invitation in Tito: https://ti.to/dcppc/may-digital-commons-workshop/admin

@raynamharris, you should have an admin invite.

I've set up the max tickets (50), added some required questions (team, CoC, video release), added the location & dates.

The rest is pending. Also, we'll need to verify/change the CoC link once we get an answer about that from our friends at HSPH (#1). The question for it is under the Data Collection option in the left sidebar menu.

**Comment by vmbrasseur** [comment]
I updated the CoC link to point to the one in this repo. We'll still need to change it if it turns out HSPH has their own.

**Comment by raynamharris** [comment]
Vicki, I'm thinking we can send the invite via regular mail, but maybe send follow up emails through tito later. Does that work?
